/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SilverJewelsRouteImport } from './routes/silver-jewels'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as PlatinumJewelsRouteImport } from './routes/platinum-jewels'
import { Route as GoldJewelsRouteImport } from './routes/gold-jewels'
import { Route as DiamondJewelsRouteImport } from './routes/diamond-jewels'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShopIndexRouteImport } from './routes/shop.index'
import { Route as ShopLadiesRouteImport } from './routes/shop.ladies'
import { Route as ShopKidsRouteImport } from './routes/shop.kids'
import { Route as ShopGentsRouteImport } from './routes/shop.gents'

const SilverJewelsRoute = SilverJewelsRouteImport.update({
  id: '/silver-jewels',
  path: '/silver-jewels',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatinumJewelsRoute = PlatinumJewelsRouteImport.update({
  id: '/platinum-jewels',
  path: '/platinum-jewels',
  getParentRoute: () => rootRouteImport,
} as any)
const GoldJewelsRoute = GoldJewelsRouteImport.update({
  id: '/gold-jewels',
  path: '/gold-jewels',
  getParentRoute: () => rootRouteImport,
} as any)
const DiamondJewelsRoute = DiamondJewelsRouteImport.update({
  id: '/diamond-jewels',
  path: '/diamond-jewels',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShopRoute,
} as any)
const ShopLadiesRoute = ShopLadiesRouteImport.update({
  id: '/ladies',
  path: '/ladies',
  getParentRoute: () => ShopRoute,
} as any)
const ShopKidsRoute = ShopKidsRouteImport.update({
  id: '/kids',
  path: '/kids',
  getParentRoute: () => ShopRoute,
} as any)
const ShopGentsRoute = ShopGentsRouteImport.update({
  id: '/gents',
  path: '/gents',
  getParentRoute: () => ShopRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/diamond-jewels': typeof DiamondJewelsRoute
  '/gold-jewels': typeof GoldJewelsRoute
  '/platinum-jewels': typeof PlatinumJewelsRoute
  '/shop': typeof ShopRouteWithChildren
  '/silver-jewels': typeof SilverJewelsRoute
  '/shop/gents': typeof ShopGentsRoute
  '/shop/kids': typeof ShopKidsRoute
  '/shop/ladies': typeof ShopLadiesRoute
  '/shop/': typeof ShopIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/diamond-jewels': typeof DiamondJewelsRoute
  '/gold-jewels': typeof GoldJewelsRoute
  '/platinum-jewels': typeof PlatinumJewelsRoute
  '/silver-jewels': typeof SilverJewelsRoute
  '/shop/gents': typeof ShopGentsRoute
  '/shop/kids': typeof ShopKidsRoute
  '/shop/ladies': typeof ShopLadiesRoute
  '/shop': typeof ShopIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/diamond-jewels': typeof DiamondJewelsRoute
  '/gold-jewels': typeof GoldJewelsRoute
  '/platinum-jewels': typeof PlatinumJewelsRoute
  '/shop': typeof ShopRouteWithChildren
  '/silver-jewels': typeof SilverJewelsRoute
  '/shop/gents': typeof ShopGentsRoute
  '/shop/kids': typeof ShopKidsRoute
  '/shop/ladies': typeof ShopLadiesRoute
  '/shop/': typeof ShopIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/diamond-jewels'
    | '/gold-jewels'
    | '/platinum-jewels'
    | '/shop'
    | '/silver-jewels'
    | '/shop/gents'
    | '/shop/kids'
    | '/shop/ladies'
    | '/shop/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/diamond-jewels'
    | '/gold-jewels'
    | '/platinum-jewels'
    | '/silver-jewels'
    | '/shop/gents'
    | '/shop/kids'
    | '/shop/ladies'
    | '/shop'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/diamond-jewels'
    | '/gold-jewels'
    | '/platinum-jewels'
    | '/shop'
    | '/silver-jewels'
    | '/shop/gents'
    | '/shop/kids'
    | '/shop/ladies'
    | '/shop/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  DiamondJewelsRoute: typeof DiamondJewelsRoute
  GoldJewelsRoute: typeof GoldJewelsRoute
  PlatinumJewelsRoute: typeof PlatinumJewelsRoute
  ShopRoute: typeof ShopRouteWithChildren
  SilverJewelsRoute: typeof SilverJewelsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/silver-jewels': {
      id: '/silver-jewels'
      path: '/silver-jewels'
      fullPath: '/silver-jewels'
      preLoaderRoute: typeof SilverJewelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platinum-jewels': {
      id: '/platinum-jewels'
      path: '/platinum-jewels'
      fullPath: '/platinum-jewels'
      preLoaderRoute: typeof PlatinumJewelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gold-jewels': {
      id: '/gold-jewels'
      path: '/gold-jewels'
      fullPath: '/gold-jewels'
      preLoaderRoute: typeof GoldJewelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diamond-jewels': {
      id: '/diamond-jewels'
      path: '/diamond-jewels'
      fullPath: '/diamond-jewels'
      preLoaderRoute: typeof DiamondJewelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/': {
      id: '/shop/'
      path: '/'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/ladies': {
      id: '/shop/ladies'
      path: '/ladies'
      fullPath: '/shop/ladies'
      preLoaderRoute: typeof ShopLadiesRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/kids': {
      id: '/shop/kids'
      path: '/kids'
      fullPath: '/shop/kids'
      preLoaderRoute: typeof ShopKidsRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/gents': {
      id: '/shop/gents'
      path: '/gents'
      fullPath: '/shop/gents'
      preLoaderRoute: typeof ShopGentsRouteImport
      parentRoute: typeof ShopRoute
    }
  }
}

interface ShopRouteChildren {
  ShopGentsRoute: typeof ShopGentsRoute
  ShopKidsRoute: typeof ShopKidsRoute
  ShopLadiesRoute: typeof ShopLadiesRoute
  ShopIndexRoute: typeof ShopIndexRoute
}

const ShopRouteChildren: ShopRouteChildren = {
  ShopGentsRoute: ShopGentsRoute,
  ShopKidsRoute: ShopKidsRoute,
  ShopLadiesRoute: ShopLadiesRoute,
  ShopIndexRoute: ShopIndexRoute,
}

const ShopRouteWithChildren = ShopRoute._addFileChildren(ShopRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  DiamondJewelsRoute: DiamondJewelsRoute,
  GoldJewelsRoute: GoldJewelsRoute,
  PlatinumJewelsRoute: PlatinumJewelsRoute,
  ShopRoute: ShopRouteWithChildren,
  SilverJewelsRoute: SilverJewelsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
